server:
  port: 9008
spring:
  application:
    name: tensquare-user
  datasource: # 数据库连接四大属性
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tensquare_user?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: root
mybatis-plus:
  type-aliases-package: com.tensquare.article.pojo
  global-config:
    id-type: 1
    db-column-underline: false
    refresh-mapper: true
  configuration:
      map-underscore-to-camel-case: true
      cache-enabled: true #配置的缓存的全局开关
      lazyLoadingEnabled: true #延时加载的开关
      multipleResultSetsEnabled: true #开启延时加载，否则按需加载属性
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
# Mybatis-Plus 配置